# Server for front-end
api:
  type: 'echo'
  port: 8100
  host: '0.0.0.0'
  homePageUrl: 'https://edgecraft.k3.acornsoft.io' # URL 셋팅 필요
  pathPrefix: '/api/v1'
  secret: 'test_secret'
  langs:
    - 'ko'
    - 'en'
  langPath: './conf'
  mode: 'local' #local:개발자pc dev:kdtidc  prod:
  benchmarks:
    image: 'regi.k3.acornsoft.io/edgecraft/edge-benchmarks'
    version: '0.2.1'
    sonobuoy_image: 'regi.k3.acornsoft.io/sonobuoy/sonobuoy'
    sonobuoy_version: 'v0.56.15'
    debug: 'true'

auth:
  RESET_PASSWORD: 'edgecraft@@'

# Database
database:
  type: 'postgres'
  host: '192.168.77.43'
  port: '31000'
  database_name: 'edgecraft'
  schema_name: 'edgecraft'
  username: 'edgecraft'
  password: 'edgecraft'
  max_idle_conns: 5
  max_open_conns: 40
# Local Database
# database:
#   type: "postgres"
#   host: "localhost"
#   port: "5432"
#   database_name: "edgecraft"
#   schema_name: "edgecraft"
#   password: "edgecraft"
#   username: "edgecraft"
#   max_idle_conns: 5
#   max_open_conns: 40
