apiVersion: velero.io/v1
kind: Backup
metadata:
  labels:
    velero.io/storage-location: default
  name: {{.Name | ToLower }}
  namespace: velero
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: true
  excludedNamespaces:
    - kube-system
    - kube-node-lease
    - kube-public
    - kubernetes-dashboard
    - velero
  hooks: {}
  includeClusterResources: true
  itemOperationTimeout: 1h0m0s
  metadata: {}
  snapshotVolumes: true
  storageLocation: default
  ttl: 720h0m0s
  volumeSnapshotLocations:
    - default