{{- $ClusterName := .Cluster.Name -}}
{{- $Namespace := .Cluster.Namespace -}}
{{- $FailureDomain := .Openstack.FailureDomain -}}
{{- $KubernetesVersion := .K8s.VersionName -}}
{{- $OpenstackCloud := .Openstack.Cloud -}}
{{- $OpenstackImageName := .Openstack.ImageName -}}
{{- $OpenstackSSHKeyName := .Openstack.SSHKeyName -}}
{{- $OpenstackProviderConfB64 := .Openstack.ProviderConfB64 -}}
{{- $OpenstackCACertB64 := .Openstack.CACertB64 -}}
{{- $OpenstackLocalHostName := .Openstack.LocalHostName -}}
{{$NodeName := "{{ ds.meta_data.local_hostname }}" -}}
{{range .Nodes.WorkerSets }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KThreesConfigTemplate
metadata:
  name: {{$ClusterName}}-{{.Name}}
  namespace: {{or $Namespace "default"}}
spec:
  template:
    spec:
      agentConfig:
        nodeName: "{{$NodeName}}"
      files:
        - content: {{$OpenstackCACertB64}}
          encoding: base64
          owner: root
          path: /etc/certs/cacert
          permissions: "0600"
        - path: /etc/rancher/k3s/registries.yaml
          content: |
            mirrors:
              docker.io:
                endpoint:
                  - "https://192.168.88.206"
            configs:
              "192.168.88.206":
                tls:
                  ca_file: /etc/docker/certs.d/192.168.88.206/ca.crt
      PreK3sCommands:
        - mkdir -p /etc/docker/certs.d/192.168.88.206
        - curl -Lk https://192.168.88.206/api/v2.0/systeminfo/getcert -o /etc/docker/certs.d/192.168.88.206/ca.crt
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: {{$ClusterName}}-{{.Name}}
  namespace: {{or $Namespace "default"}}
spec:
  template:
    spec:
      cloudName: {{$OpenstackCloud}}
      flavor: {{.Flavor}}
      identityRef:
        kind: Secret
        name: {{$ClusterName}}-cloud-config
      image: {{$OpenstackImageName}}
      sshKeyName: {{$OpenstackSSHKeyName}}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{$ClusterName}}-{{.Name}}
  namespace: {{or $Namespace "default"}}
spec:
  clusterName: {{$ClusterName}}
  replicas: {{.NodeCount}}
  selector:
    matchLabels: null
  template:
    spec:
      clusterName: {{$ClusterName}}
      failureDomain: {{or $FailureDomain "nova"}}
      version: v{{$KubernetesVersion}}
      bootstrap:
        configRef:
          name: {{$ClusterName}}-{{.Name}}
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KThreesConfigTemplate
      infrastructureRef:
        name: {{$ClusterName}}-{{.Name}}
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
        kind: OpenStackMachineTemplate
{{end}}