{{$ClusterName := .Cluster.Name -}}
{{$Namespace := .Cluster.Namespace -}}
{{$FailureDomain := .Openstack.FailureDomain -}}
{{$KubernetesVersion := .K8s.VersionName -}}
{{$OpenstackCloud := .Openstack.Cloud -}}
{{$OpenstackImageName := .Openstack.ImageName -}}
{{$OpenstackSSHKeyName := .Openstack.SSHKeyName -}}
{{$OpenstackProviderConfB64 := .Openstack.ProviderConfB64 -}}
{{$OpenstackCACertB64 := .Openstack.CACertB64 -}}
{{$OpenstackLocalHostName := .Openstack.LocalHostName -}}
{{$OpenstackInstanceId := .Openstack.InstanceId -}}
{{$OpenstackCloudControllerManagerRoles := .Openstack.CloudControllerManagerRoles -}}
{{$OpenstackCloudControllerManagerRoleBindings := .Openstack.CloudControllerManagerRoleBindings -}}
{{$OpenstackPpenstackCloudControllerManagerDS := .Openstack.PpenstackCloudControllerManagerDS -}}
{{$K8sRegistry := "registry.k8s.io" -}}
{{ if ge (semver $KubernetesVersion | (semver "1.25.0").Compare) 0 -}}
{{$K8sRegistry = "k8s.gcr.io" -}}
{{ end -}}

apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: {{$ClusterName}}-{{(index .Nodes.MasterSets 0).Name}}-v{{ $KubernetesVersion | replace "." "-" }}
  namespace: {{or $Namespace "default"}}
spec:
  template:
    spec:
      cloudName: {{$OpenstackCloud}}
      flavor: {{(index .Nodes.MasterSets 0).Flavor}}
      identityRef:
        kind: Secret
        name: {{$ClusterName}}-cloud-config
      image: {{$OpenstackImageName}}
      sshKeyName: {{$OpenstackSSHKeyName}}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{$ClusterName}}-{{(index .Nodes.MasterSets 0).Name}}
  namespace: {{or $Namespace "default"}}
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      {{if eq true .EtcdStorage.Etcd.UseExternalEtcd}}
      etcd:
        external:"defaul"
          endpoints:
          {{with .EtcdStorage.Etcd.Endpoints}}
            {{ range . }}
            - https://{{.}} # - https://10.0.0.230:2379
            {{ end}}
          {{end}}
          caFile: {{.EtcdStorage.Etcd.CAFile}} # /etc/kubernetes/pki/etcd/ca.crt
          certFile: {{.EtcdStorage.Etcd.CertFile}} # /etc/kubernetes/pki/apiserver-etcd-client.crt
          keyFile: {{.EtcdStorage.Etcd.KeyFile}} # /etc/kubernetes/pki/apiserver-etcd-client.key
      {{end -}}  
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
      imageRepository: {{$K8sRegistry}}
    files:
      - content: {{$OpenstackCloudControllerManagerRoles}}
        encoding: base64
        owner: root
        path: /etc/kubernetes/addon/openstack/cloud-controller-manager-roles.yaml
        permissions: "0600"
      - content: {{$OpenstackCloudControllerManagerRoleBindings}}
        encoding: base64
        owner: root
        path: /etc/kubernetes/addon/openstack/cloud-controller-manager-role-bindings.yaml
        permissions: "0600"
      - content: {{$OpenstackPpenstackCloudControllerManagerDS}}
        encoding: base64
        owner: root
        path: /etc/kubernetes/addon/openstack/openstack-cloud-controller-manager-ds.yaml
        permissions: "0600"
      - content: {{$OpenstackProviderConfB64}}
        encoding: base64
        owner: root
        path: /etc/kubernetes/cloud.conf
        permissions: "0600"
      - path: /etc/containerd/config.toml
        content: |
          version = 2
          imports = ["/etc/containerd/conf.d/*.toml"]
          [plugins]
            [plugins."io.containerd.grpc.v1.cri"]
              sandbox_image = "registry.k8s.io/pause:3.9"
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
              runtime_type = "io.containerd.runc.v2"
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              SystemdCgroup = true
              [plugins."io.containerd.grpc.v1.cri".registry]
                config_path = "/etc/containerd/certs.d"
      - path: /etc/containerd/certs.d/192.168.88.206/hosts.toml
        content: |
          server = "https://192.168.88.206"

          [host."https://192.168.88.206"]
            ca = "/etc/docker/certs.d/192.168.88.206/ca.crt"
      - path: /etc/containerd/certs.d/docker.io/hosts.toml
        content: |
          server = "https://docker.io"

          [host."https://192.168.88.206/v2/docker.io/"]
            capabilities = ["pull", "resolve"]
            ca = "/etc/docker/certs.d/192.168.88.206/ca.crt"
            override_path = true
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ $OpenstackInstanceId }}'
        name: "{{ $OpenstackLocalHostName }}"
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ $OpenstackInstanceId }}'
        name: "{{ $OpenstackLocalHostName }}"
    # calico preinstall, notice if closed cloud environment
    preKubeadmCommands:
      - mkdir -p /etc/docker/certs.d/192.168.88.206
      - curl -Lk https://192.168.88.206/api/v2.0/systeminfo/getcert -o /etc/docker/certs.d/192.168.88.206/ca.crt
    postKubeadmCommands:
      - kubectl --kubeconfig=/etc/kubernetes/admin.conf create secret -n kube-system generic cloud-config --from-file=/etc/kubernetes/cloud.conf
      - kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /etc/kubernetes/addon/openstack/cloud-controller-manager-roles.yaml
      - kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /etc/kubernetes/addon/openstack/cloud-controller-manager-role-bindings.yaml
      - kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /etc/kubernetes/addon/openstack/openstack-cloud-controller-manager-ds.yaml
      {{ .K8s.MasterExtraConfig.PostKubeadmCommands }}
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
      kind: OpenStackMachineTemplate
      name: {{$ClusterName}}-{{(index .Nodes.MasterSets 0).Name}}-v{{ $KubernetesVersion | replace "." "-" }}
  replicas: {{(index .Nodes.MasterSets 0).NodeCount}}
  version: v{{$KubernetesVersion}}