{{$ClusterName := .Cluster.Name -}}
{{$Namespace := .Cluster.Namespace -}}
{{$FailureDomain := .Openstack.FailureDomain -}}
{{$KubernetesVersion := .K8s.VersionName -}}
{{$OpenstackCloud := .Openstack.Cloud -}}
{{$OpenstackImageName := .Openstack.ImageName -}}
{{$OpenstackSSHKeyName := .Openstack.SSHKeyName -}}
{{$OpenstackProviderConfB64 := .Openstack.ProviderConfB64 -}}
{{$OpenstackCACertB64 := .Openstack.CACertB64 -}}
{{$OpenstackLocalHostName := .Openstack.LocalHostName -}}
apiVersion: v1
data:
  cacert: {{$OpenstackCACertB64}}
  clouds.yaml: {{.Openstack.YamlB64}}
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: {{$ClusterName}}-cloud-config
  namespace: {{or $Namespace "default"}}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackMachineTemplate
metadata:
  name: {{$ClusterName}}-{{(index .Nodes.MasterSets 0).Name}}
  namespace: {{or $Namespace "default"}}
spec:
  template:
    spec:
      cloudName: {{$OpenstackCloud}}
      flavor: {{(index .Nodes.MasterSets 0).Flavor}}
      identityRef:
        kind: Secret
        name: {{$ClusterName}}-cloud-config
      image: {{$OpenstackImageName}}
      sshKeyName: {{$OpenstackSSHKeyName}}
---
{{range .Nodes.WorkerSets -}}
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: MicroK8sConfigTemplate
metadata:
  name: {{$ClusterName}}-{{.Name}}
  namespace: {{or $Namespace "default"}}
spec:
  template:
    spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackMachineTemplate
metadata:
  name: {{$ClusterName}}-{{.Name}}
  namespace: {{or $Namespace "default"}}
spec:
  template:
    spec:
      cloudName: {{$OpenstackCloud}}
      flavor: {{.Flavor}}
      identityRef:
        kind: Secret
        name: {{$ClusterName}}-cloud-config
      image: {{$OpenstackImageName}}
      sshKeyName: {{$OpenstackSSHKeyName}}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{$ClusterName}}-{{.Name}}
  namespace: {{or $Namespace "default"}}
spec:
  clusterName: {{$ClusterName}}
  replicas: {{.NodeCount}}
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: MicroK8sConfigTemplate
          name: {{$ClusterName}}-{{.Name}}
      clusterName: {{$ClusterName}}
      failureDomain: {{or $FailureDomain "nova"}}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
        kind: OpenStackMachineTemplate
        name: {{$ClusterName}}-{{.Name}}
      version: v{{$KubernetesVersion}}
---
{{- end}}
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: MicroK8sControlPlane
metadata:
  name: {{$ClusterName}}-{{(index .Nodes.MasterSets 0).Name}}
  namespace: {{or $Namespace "default"}}
spec:
  controlPlaneConfig:
    initConfiguration:
      addons:
        - dns
        - ingress
      #joinTokenTTLInSecs: 9000
  machineTemplate:
    infrastructureTemplate:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
      kind: OpenStackMachineTemplate
      name: {{$ClusterName}}-{{(index .Nodes.MasterSets 0).Name}}
  replicas: {{(index .Nodes.MasterSets 0).NodeCount}}
  version: v{{$KubernetesVersion}}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackCluster
metadata:
  name: {{$ClusterName}}
  namespace: {{or $Namespace "default"}}
spec:
  {{if eq true .Openstack.UseBastionHost}}
  bastion:
    enabled: true
    instance:
      flavor: {{.Openstack.BastionFlavor }}
      image:  {{.Openstack.BastionImageName }}
      sshKeyName: {{.Openstack.BastionSSHKeyName }}
      {{if ne "" .Openstack.BastionFloatingIP}}
      floatingIP: {{.Openstack.BastionFloatingIP}}
      {{end}}
  {{end -}}
  allowAllInClusterTraffic: true
  apiServerLoadBalancer:
    enabled: {{.Nodes.UseLoadbalancer}}
  cloudName: {{$OpenstackCloud}}
  dnsNameservers:
    - {{.Openstack.DNSNameServers}}
  externalNetworkId: {{or .Openstack.ExternalNetworkID "public"}}
  identityRef:
    kind: Secret
    name: {{$ClusterName}}-cloud-config
  managedSecurityGroups: true
  nodeCidr: {{.Openstack.NodeCidr}}
  {{- if ne "" .Openstack.APIServerFloatingIP}}
  apiServerFloatingIP: {{.Openstack.APIServerFloatingIP}}
  {{- end}}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{$ClusterName}}
  namespace: {{or $Namespace "default"}}
  labels:
    csiNfsChart: enabled
    dashboardChart: enabled
    veleroChart: enabled
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - {{.K8s.PodCidr}}
    {{if ne "" .K8s.SvcCidr -}}
    services:
      cidrBlocks:
        - {{.K8s.SvcCidr}}
    {{end -}}
    serviceDomain: {{or .K8s.SvcDomain "cluster.local"}}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: MicroK8sControlPlane
    name: {{$ClusterName}}-{{(index .Nodes.MasterSets 0).Name}}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
    kind: OpenStackCluster
    name: {{$ClusterName}}