{{$ClusterName := .Cluster.Name -}}
{{$Namespace := .Cluster.Namespace -}}
{{$FailureDomain := .Openstack.FailureDomain -}}
{{$KubernetesVersion := .K8s.VersionName -}}
{{$OpenstackCloud := .Openstack.Cloud -}}
{{$OpenstackImageName := .Openstack.ImageName -}}
{{$OpenstackSSHKeyName := .Openstack.SSHKeyName -}}
apiVersion: v1
data:
  cacert: {{.Openstack.CACertB64}}
  clouds.yaml: {{.Openstack.YamlB64}}
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: {{$ClusterName}}-cloud-config
  namespace: {{or $Namespace "default"}}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{$ClusterName}}
  namespace: {{or $Namespace "default"}}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - {{.K8s.PodCidr}}
    {{if ne "" .K8s.SvcCidr -}}
    services:
      cidrBlocks:
        - {{.K8s.SvcCidr}}
    {{end -}}
    serviceDomain: {{or .K8s.SvcDomain "cluster.local"}}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{$ClusterName}}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
    kind: OpenStackCluster
    name: {{$ClusterName}}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackCluster
metadata:
  name: {{$ClusterName}}
  namespace: {{or $Namespace "default"}}
spec:
  {{ if eq true .Openstack.UseBastionHost -}}
  bastion:
    enabled: true
    instance:
      flavor: {{.Openstack.BastionFlavor }}
      image:  {{.Openstack.BastionImageName }}
      sshKeyName: {{.Openstack.BastionSSHKeyName }}
      {{if ne "" .Openstack.BastionFloatingIP -}}
      floatingIP: {{.Openstack.BastionFloatingIP}}
      {{end -}}
  {{ end -}}
  apiServerLoadBalancer:
    enabled: {{.Nodes.UseLoadbalancer}}
  cloudName: {{$OpenstackCloud}}
  dnsNameservers:
    - {{.Openstack.DNSNameServers}}
  externalNetworkId: {{or .Openstack.ExternalNetworkID "public"}}
  identityRef:
    kind: Secret
    name: {{$ClusterName}}-cloud-config
  managedSecurityGroups: true
  nodeCidr: {{.Openstack.NodeCidr}}
  {{if ne "" .Openstack.APIServerFloatingIP -}}
  apiServerFloatingIP: {{.Openstack.APIServerFloatingIP}}
  {{end -}}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{$ClusterName}}-md-0
  namespace: {{or $Namespace "default"}}
spec:
  template:
    spec:
      files:
        - content: {{.Openstack.ProviderConfB64}}
          encoding: base64
          owner: root
          path: /etc/kubernetes/cloud.conf
          permissions: "0600"
        - content: {{.Openstack.CACertB64}}
          encoding: base64
          owner: root
          path: /etc/certs/cacert
          permissions: "0600"
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-config: /etc/kubernetes/cloud.conf
            cloud-provider: openstack
          name: "{{ .Openstack.LocalHostName }}"
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{$ClusterName}}-control-plane
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      {{ if eq true .EtcdStorage.Etcd.UseExternalEtcd -}}
      etcd:
        external:"defaul"
          endpoints:
          {{with .EtcdStorage.Etcd.Endpoints -}}
            {{ range . }}
            - https://{{.}} # - https://10.0.0.230:2379
            {{ end -}}
          {{end -}}
          caFile: {{.EtcdStorage.Etcd.CAFile}} # /etc/kubernetes/pki/etcd/ca.crt
          certFile: {{.EtcdStorage.Etcd.CertFile}} # /etc/kubernetes/pki/apiserver-etcd-client.crt
          keyFile: {{.EtcdStorage.Etcd.KeyFile}} # /etc/kubernetes/pki/apiserver-etcd-client.key
      {{ end -}}  
      apiServer:
        extraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        extraVolumes:
          - hostPath: /etc/kubernetes/cloud.conf
            mountPath: /etc/kubernetes/cloud.conf
            name: cloud
            readOnly: true
      controllerManager:
        extraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        extraVolumes:
          - hostPath: /etc/kubernetes/cloud.conf
            mountPath: /etc/kubernetes/cloud.conf
            name: cloud
            readOnly: true
          - hostPath: /etc/certs/cacert
            mountPath: /etc/certs/cacert
            name: cacerts
            readOnly: true
      imageRepository: k8s.gcr.io
    files:
      - content: {{.Openstack.ProviderConfB64}}
        encoding: base64
        owner: root
        path: /etc/kubernetes/cloud.conf
        permissions: "0600"
      - content: {{.Openstack.CACertB64}}
        encoding: base64
        owner: root
        path: /etc/certs/cacert
        permissions: "0600"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        name: "{{ .Openstack.LocalHostName }}"
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        name: "{{ .Openstack.LocalHostName }}"
    # calico preinstall, notice if closed cloud environment
    postKubeadmCommands:
      - kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
      kind: OpenStackMachineTemplate
      name: {{$ClusterName}}-control-plane
  replicas: {{(index .Nodes.MasterSets 0).NodeCount}}
  version: {{$KubernetesVersion}}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: {{$ClusterName}}-control-plane
spec:
  template:
    spec:
      cloudName: {{$OpenstackCloud}}
      flavor: {{(index .Nodes.MasterSets 0).Flavor}}
      identityRef:
        kind: Secret
        name: {{$ClusterName}}-cloud-config
      image: {{$OpenstackImageName}}
      sshKeyName: {{$OpenstackSSHKeyName}}
{{range .Nodes.WorkerSets -}}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{$ClusterName}}-{{.Name}}
  namespace: {{or $Namespace "default"}}
spec:
  clusterName: {{$ClusterName}}
  replicas: {{.NodeCount}}
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{$ClusterName}}-md-0
      clusterName: {{$ClusterName}}
      failureDomain: {{or $FailureDomain "nova"}}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
        kind: OpenStackMachineTemplate
        name: {{$ClusterName}}-{{.Name}}
      version: {{$KubernetesVersion}}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: {{$ClusterName}}-{{.Name}}
spec:
  template:
    spec:
      cloudName: {{$OpenstackCloud}}
      flavor: {{.Flavor}}
      identityRef:
        kind: Secret
        name: {{$ClusterName}}-cloud-config
      image: {{$OpenstackImageName}}
      sshKeyName: {{$OpenstackSSHKeyName}}
{{end -}}