apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgecraft-api
  namespace: edgecraft
  labels:
    app: edgecraft-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgecraft-api
  template:
    metadata:
      labels:
        app: edgecraft-api
    spec:
      serviceAccountName: edgecraft
      containers:
        - name: edgecraft-api
          image: ghcr.io/acornsoft-edgecraft/edgecraft-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8100
