# External ETCD 처리 방식 : https://main.cluster-api.sigs.k8s.io/tasks/external-etcd.html
# TODO: Bastion Server 는 어떻게?
# TODO: External ETCD는 어떻게? (사전에 구성한 경우만 가능)

apiVersion: v1
data:
  cacert: ${OPENSTACK_CLOUD_CACERT_B64} ###### apply cacert base64
  clouds.yaml: ${OPENSTACK_CLOUD_YAML_B64} ##### apply cloud.yaml base64
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: ${CLUSTER_NAME}-cloud-config ##### apply cluster name
  namespace: default ##### apply namespace
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0 ##### apply cluster name
  namespace: default ##### apply namespace
spec:
  template:
    spec:
      files:
        - content: ${OPENSTACK_CLOUD_PROVIDER_CONF_B64} ##### apply openstack provider config base64
          encoding: base64
          owner: root
          path: /etc/kubernetes/cloud.conf
          permissions: "0600"
        - content: ${OPENSTACK_CLOUD_CACERT_B64} ##### apply cacert base64
          encoding: base64
          owner: root
          path: /etc/certs/cacert
          permissions: "0600"
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-config: /etc/kubernetes/cloud.conf
            cloud-provider: openstack
          name: "{{ local_hostname }}" ##### apply local host name
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME} ##### apply cluster name
  namespace: default ##### apply namespace
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16 ##### apply pod cidr
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: ${CLUSTER_NAME}-control-plane ##### apply cluster name
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
    kind: OpenStackCluster
    name: ${CLUSTER_NAME} ##### apply cluster name
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: ${CLUSTER_NAME}-md-0 ##### apply cluster name
  namespace: default ##### apply namespace
spec:
  clusterName: ${CLUSTER_NAME} ##### apply cluster name
  replicas: ${WORKER_MACHINE_COUNT} ##### apply worker machine count
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: ${CLUSTER_NAME}-md-0 ##### apply cluster name
      clusterName: ${CLUSTER_NAME} ##### apply cluster name
      failureDomain: ${OPENSTACK_FAILURE_DOMAIN} ##### apply failure doman, default 'nova'
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
        kind: OpenStackMachineTemplate
        name: ${CLUSTER_NAME}-md-0 ##### apply cluster name
      version: ${KUBERNETES_VERSION} ##### apply kubernetes version
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane ##### apply cluster name
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        extraVolumes:
          - hostPath: /etc/kubernetes/cloud.conf
            mountPath: /etc/kubernetes/cloud.conf
            name: cloud
            readOnly: true
      controllerManager:
        extraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        extraVolumes:
          - hostPath: /etc/kubernetes/cloud.conf
            mountPath: /etc/kubernetes/cloud.conf
            name: cloud
            readOnly: true
          - hostPath: /etc/certs/cacert
            mountPath: /etc/certs/cacert
            name: cacerts
            readOnly: true
      imageRepository: k8s.gcr.io ##### notice v1alpha5에는 존재
    files:
      - content: ${OPENSTACK_CLOUD_PROVIDER_CONF_B64} ##### apply openstack provider config base64
        encoding: base64
        owner: root
        path: /etc/kubernetes/cloud.conf
        permissions: "0600"
      - content: ${OPENSTACK_CLOUD_CACERT_B64} ##### apply cacert base64
        encoding: base64
        owner: root
        path: /etc/certs/cacert
        permissions: "0600"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        name: "{{ local_hostname }}" ##### apply local host name
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        name: "{{ local_hostname }}" ##### apply local host name
    # calico preinstall, notice if closed cloud environment
    postKubeadmCommands:
      - kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
      kind: OpenStackMachineTemplate
      name: ${CLUSTER_NAME}-control-plane ##### apply cluster name
  replicas: ${CONTROL_PLANE_MACHINE_COUNT} ##### apply master node count
  version: ${KUBERNETES_VERSION} ##### apply kubernetes version
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackCluster
metadata:
  name: ${CLUSTER_NAME} ##### apply cluster name
  namespace: default ##### apply namespace
spec:
  apiServerLoadBalancer:
    enabled: true ##### apply loadbalancer, default true
  cloudName: ${OPENSTACK_CLOUD} ##### apply cloud name
  dnsNameservers:
    - ${OPENSTACK_DNS_NAMESERVERS} ##### apply dns nameservers
  externalNetworkId: ${OPENSTACK_EXTERNAL_NETWORK_ID} ##### apply external network id, default public
  identityRef:
    kind: Secret
    name: ${CLUSTER_NAME}-cloud-config ##### apply cluster name
  managedSecurityGroups: true
  nodeCidr: 10.6.0.0/24 ##### apply node cidr, notice 화면에 매칭되는 곳이 없음, 화면의 ServiceCIDR도 대상이 없음.
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-control-plane ##### apply cluster name, notice v1alpha5와 다름 (name: os-cluster-md-0)
spec:
  template:
    spec:
      cloudName: ${OPENSTACK_CLOUD} ##### apply cloud name
      flavor: ${OPENSTACK_CONTROL_PLANE_MACHINE_FLAVOR} ##### apply control plane machine flavor
      identityRef:
        kind: Secret
        name: ${CLUSTER_NAME}-cloud-config ##### apply cluster name
      image: ${OPENSTACK_IMAGE_NAME} ##### apply host image name
      sshKeyName: ${OPENSTACK_SSH_KEY_NAME} ##### apply ssh key name
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
spec:
  template:
    spec:
      cloudName: ${OPENSTACK_CLOUD}
      flavor: ${OPENSTACK_NODE_MACHINE_FLAVOR}
      identityRef:
        kind: Secret
        name: ${CLUSTER_NAME}-cloud-config
      image: ${OPENSTACK_IMAGE_NAME}
      sshKeyName: ${OPENSTACK_SSH_KEY_NAME}
