apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgecraft-api
  namespace: edgecraft
  labels:
    app: edgecraft-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgecraft-api
  template:
    metadata:
      labels:
        app: edgecraft-api
    spec:
      containers:
      - name: edgecraft-api
        image: 192.168.77.30/edgecraft/edgecraft-api:v0.3.0-beta.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8100