# publish docker image
# - https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images
# - https://github.com/docker/build-push-action

name: Build & Push
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (optional)'
        required: false
  push:
    tags:
      - v*
jobs:
  build_and_push:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        id: variables
        run: |
          PROJECT="edgecraft"
          TAG="edgecraft-api"
          VERSION="${{ github.event.inputs.version }}"
          REGISTRY="ghcr.io"
          if [[ $VERSION == "" ]]; then
            GITHUB_REF="${{ github.ref }}"
            if [[ $GITHUB_REF == refs/tags/* ]]; then
              VERSION=${GITHUB_REF#refs/tags/}
            elif [[ $GITHUB_REF == refs/heads/* ]]; then
              VERSION="$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')-$(date '+%Y%m%d')"
            elif [[ $GITHUB_REF == refs/pull/* ]]; then
              VERSION="pr-${{ github.event.number }}"
            fi
          fi
          echo ::set-output name=prefix::${REGISTRY}/${PROJECT}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tag::${TAG}
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Login GHCR
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image [${{steps.variables.outputs.tag}}]
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{steps.variables.outputs.prefix}}.${{steps.variables.outputs.tag}}:${{steps.variables.outputs.version}}
            ${{steps.variables.outputs.prefix}}.${{steps.variables.outputs.tag}}:latest